#!/usr/bin/env bash
required_python_version="3.6.0"
root="$(git rev-parse --show-toplevel)"
venv_path="$root/venv"
requirements_txt="$root/scripts/requirements.txt"

python_version="$(python3 --version 2>&1 | awk '{print $2}')"

is_bigger() {
    [[ "$(printf '%s\n' "$1" "$2" | sort -V | tail -n1)" == "$1" ]]
}

if ! is_bigger "$python_version" "$required_python_version"; then
    printf \
        'Python version `%s` or higher is required. Found: `%s`' \
        "$required_python_version" \
        "$python_version"
    exit 1
fi

if [[ ! -d "$venv_path" ]]; then
    python3 -m venv "$venv_path"
fi
. "$venv_path/bin/activate"
pip install --upgrade pip
pip install -r "$requirements_txt"

python "$@"
